# Generated by Django 5.0.1 on 2024-04-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='place',
            field=models.CharField(max_length=25),
        ),
    ]
